// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jerizehxtzhhqarpyowx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Implcml6ZWh4dHpoaHFhcnB5b3d4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4ODUzNjgsImV4cCI6MjA1MzQ2MTM2OH0.D_mqqB8LAnGWudpR-FwytjulDEbQIK7-RsaRzyMA9n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);